version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - not_null

  - name: stg_image_invoices
    columns:
      - name: invoice_id
        tests:
          - unique
          - not_null
      - name: invoice_date
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: employee_name
        tests:
          - not_null
      - name: price
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null
      - name: image_type
        tests:
          - not_null
